app = "flex"
port = 4789
level = "debug"

[etcd]
    endpoints = [
       	"localhost:2379",
		# "localhost:2382",
		# "localhost:2383",
    ]
[[topics]]
	topic = "topic1" 
	buffer = "queue"
	router = "hash"

[[topics]]
	topic = "topic2" 
	buffer = "queue"
	router = "round-robin"