app = "flex"

buffer = "queue"
router = "hash"
log-level = "debug"

[etcd]
    endpoints = [
       	"localhost:2381",
		"localhost:2382",
		"localhost:2383",
    ]
[[topics]]
	topic = "topic1" 
	buffer = "queue"
	router = "hash"

[[topics]]
	topic = "topic1" 
	buffer = "queue"
	router = "round-robin"